INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000001','Aachen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000004','Altenbeken',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000009','Ansbach',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000013','Augsburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8011044','Anklam',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000331','Andernach',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010018','Bad Kleinen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000935','Bad Bevensen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010022','Bad Schandau',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000025','Bamberg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010255','Berlin Ostbahnhof',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8011102','Berlin Gesundbrunnen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8011113','Berlin Südkreuz',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8011162','Berlin Ostkreuz',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000031','Bensheim',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010033','Bergen auf Rügen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010404','Berlin-Spandau',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8013470','Bernau(b Berlin)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000036','Bielefeld Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010405','Berlin Wannsee',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010050','Bitterfeld',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000039','Bingen(Rhein) Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000049','Braunschweig Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000050','Bremen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000044','Bonn Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000059','Bünde(Westf)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000058','Büchen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010066','Bützow',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000064','Celle',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000070','Delmenhorst',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000078','Donauwörth',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000080','Dortmund Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010085','Dresden Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010089','Dresden-Neustadt',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000084','Düren',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000085','Düsseldorf Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000082','Düsseldorf Flughafen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000086','Duisburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000093','Elze(Han)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8001768','Emden Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8001767','Emden Außenhafen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010097','Eisenach',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000098','Essen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010101','Erfurt Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000112','Friedrichshafen Stadt',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000108','Freilassing',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000115','Fulda',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000124','Gießen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002206','Geilenkirchen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000118','Gelsenkirchen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000128','Göttingen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010136','Gotha',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002461','Gütersloh Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000142','Hagen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002553','Hamburg-Altona',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002548','Hamburg Dammtor',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000147','Hamburg-Harburg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002554','Hamburg-Bergedorf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010159','Halle(Saale)Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000150','Hanau Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000152','Hannover Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000162','Herford',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002806','Herzogenrath',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010133','Jena-Göschwitz',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8011956','Jena Paradies',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003184','Karlsruhe-Durlach',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000199','Kiel Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003368','Köln Messe/Deutz',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003330','Köln/Bonn Flughafen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000206','Koblenz Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003400','Konstanz',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003494','Lahr(Schwarzw)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000213','Kreiensen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000211','Krefeld Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010195','Köthen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000225','Leer(Ostfriesl)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003515','Landstuhl',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003680','Limburg Süd',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010205','Leipzig Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000230','Lindau Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003701','Lingen(Ems)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000238','Lüneburg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000571','Lippstadt',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000237','Lübeck Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000337','Marburg(Lahn)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003866','Marienhafe',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000240','Mainz Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010222','Lutherstadt Wittenberg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000261','München Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000253','Mönchengladbach Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000667','Montabaur',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8004158','München-Pasing',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000262','München Ost',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000263','Münster(Westf)Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000271','Neumünster',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000275','Neustadt(Weinstr)Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8004449','Norddeich',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8007768','Norddeich Mole',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000800','Norden',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000283','Northeim(Han)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000284','Nürnberg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000286','Oberhausen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8011191','Ostseebad Binz',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000294','Osnabrück Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000301','Plattling',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010268','Pasewalk',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000297','Paderborn Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8004751','Papenburg(Ems)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8004885','Prien a Chiemsee',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8012666','Potsdam Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010282','Prenzlau',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000309','Regensburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000316','Rheine',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000310','Remagen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8012763','Ribnitz-Damgarten West',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010304','Rostock Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000318','Rheydt Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010297','Riesa',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8005556','Siegburg/Bonn',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000076','Soest',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8005644','St Georgen(Schwarzw)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000095','Straubing',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010338','Stralsund Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000116','Traunstein',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000122','Treuchtlingen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8005927','Tutzing',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000129','Treysa',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000168','Uelzen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010355','Velgast',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8006076','Verden(Aller)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000174','Viersen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000368','Wabern(Bz Kassel)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000192','Wanne-Eickel Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000196','Warburg(Westf)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010368','Weißenfels',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010366','Weimar',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000377','Weinheim(Bergstr)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010382','Wittenberge',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000250','Wiesbaden Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000257','Worms Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000266','Wuppertal Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000774','Baden-Baden',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000943','Biberach(Riß)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000055','Bruchsal',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000077','Donaueschingen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000107','Freiburg(Breisgau) Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000156','Heidelberg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000191','Karlsruhe Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000244','Mannheim Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8004124','Müllheim(Baden)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000290','Offenburg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000302','Plochingen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000880','Radolfzell',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8004965','Ravensburg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000073','Singen(Hohentwiel)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000096','Stuttgart Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000170','Ulm Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8006053','Vaihingen(Enz)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000366','Villingen(Schwarzw)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8006272','Weil am Rhein',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8006421','Wiesloch-Walldorf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000010','Aschaffenburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8001338','Coburg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8001844','Erlangen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002187','Garmisch-Partenkirchen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000139','Günzburg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000183','Ingolstadt Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000228','Lichtenfels',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8004185','Murnau',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8006730','Neu-Ulm',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000298','Passau Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000320','Rosenheim',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000220','Weilheim(Oberbay)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000260','Würzburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010004','Angermünde',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8011160','Berlin Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010406','Berlin Zoologischer Garten',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010060','Brandenburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010093','Eberswalde Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000020','Bad Hersfeld',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000068','Darmstadt Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000090','Eichenberg',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003200','Kassel-Wilhelmshöhe',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000891','Schlüchtern',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010139','Greifswald',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010216','Ludwigslust',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010324','Schwerin Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8013236','Warnemünde',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010396','Züssow',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000483','Alfeld(Leine)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000169','Hildesheim Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003545','Langenhagen Mitte',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8003978','Meppen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000279','Nienburg(Weser)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000291','Oldenburg(Oldb)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8006552','Wolfsburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000041','Bochum Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8001839','Erkelenz',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000149','Hamm(Westf)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000207','Köln Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000252','Minden(Westf)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000307','Recklinghausen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000087','Solingen Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000189','Kaiserslautern Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000323','Saarbrücken Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8012183','Leipzig/Halle Flughafen',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010224','Magdeburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002549','Hamburg Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8070003','Frankfurt(M) Flughafen Fernbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000105','Frankfurt(Main)Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002041','Frankfurt(Main)Süd',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8002042','Frankfurt(Main)West',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000111','Friedberg(Hess)',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8000176','Homburg(Saar)Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010240','Naumburg(Saale)Hbf',' ','ICE');
INSERT INTO public.stations(eva_number, station_name, station_prefix, station_code)VALUES ('8010334','Stendal',' ','ICE');
